console.log("Conectado");
const datos = {
  bienes: [
    {
      id: 1,
      nombre: "Tu perfecto hogar",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa1.jpg",
      codigo: 1234,
      precio: 60000000,
      ubicacion: "Cali",
      area: "75 m2",
      detalles: "Buena ubicacion, excelente vista",
    },
    {
      id: 2,
      nombre: "Casa Colonial",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa2.jpg",
      codigo: 1008,
      precio: 180000000,
      ubicacion: "Cartagena",
      area: "180 m2",
      detalles: "Casa histórica restaurada, con detalles arquitectónicos únicos y patio interior.",
    },
    {
      id: 3,
      nombre: "Apartamento de Lujo",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa3.jpg",
      codigo: 1009,
      precio: 900000000,
      ubicacion: "Bogotá",
      area: "300 m2",
      detalles: "Espectacular apartamento de alto standing con acabados de primera calidad y vistas panorámicas.",
    },
    {
      id: 4,
      nombre: "Finca Ganadera",
      categoria: "Finca",
      imagen: "C:\ProyectoFinal/imagenes/casa4.jpg",
      codigo: 1010,
      precio: 1200000000,
      ubicacion: "Antioquia",
      area: "500 ha",
      detalles: "Finca productiva con instalaciones para ganado, cultivos y agua propia.",
    },
    {
      id: 5,
      nombre: "Edificio de Oficinas",
      categoria: "Edificio",
      imagen: "C:\ProyectoFinal/imagenes/casa5.jpg",
      codigo: 1011,
      precio: 5000000000,
      ubicacion: "Medellín",
      area: "2000 m2",
      detalles: "Edificio corporativo con múltiples niveles, estacionamiento y acceso a servicios empresariales.",
    },
    {
      id: 6,
      nombre: "Casa Campestre",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa6.jpg",
      codigo: 1012,
      precio: 350000000,
      ubicacion: "Cundinamarca",
      area: "250 m2",
      detalles: "Casa en entorno natural con amplias áreas verdes y espacios para el esparcimiento familiar.",
    },
    {
      id: 7,
      nombre: "Local Comercial en Centro Comercial",
      categoria: "Local",
      imagen: "C:\ProyectoFinal/imagenes/casa7.jpg",
      codigo: 1013,
      precio: 500000000,
      ubicacion: "Bogotá",
      area: "150 m2",
      detalles: "Local estratégicamente ubicado dentro de un reconocido centro comercial, con alto tráfico de clientes.",
    },
    {
      id: 8,
      nombre: "Terreno Industrial",
      categoria: "Terreno",
      imagen: "C:\ProyectoFinal/imagenes/casa8.jpg",
      codigo: 1014,
      precio: 800000000,
      ubicacion: "Valle del Cauca",
      area: "1000 m2",
      detalles: "Terreno apto para desarrollo industrial, con acceso a servicios básicos y buena conectividad.",
    },
    {
      id: 9,
      nombre: "Casa de Playa",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa9.jpg",
      codigo: 1015,
      precio: 600000000,
      ubicacion: "Santa Marta",
      area: "200 m2",
      detalles: "Casa junto al mar con acceso directo a la playa, ideal para vacaciones y descanso.",
    },
    {
      id: 10,
      nombre: "Apartamento Ejecutivo",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa10.jpg",
      codigo: 1016,
      precio: 450000000,
      ubicacion: "Cali",
      area: "150 m2",
      detalles: "Apartamento moderno y funcional en zona residencial exclusiva, con servicios cercanos.",
    },
    {
      id: 11,
      nombre: "Hotel Boutique",
      categoria: "Hotel",
      imagen: "C:\ProyectoFinal/imagenes/casa11.jpg",
      codigo: 1017,
      precio: 3500000000,
      ubicacion: "Cartagena",
      area: "1000 m2",
      detalles: "Hotel boutique de lujo con diseño único y servicios premium, ubicado en el casco histórico.",
    },
    {
      id: 12,
      nombre: "Edificio Residencial",
      categoria: "Edificio",
      imagen: "C:\ProyectoFinal/imagenes/casa12.jpg",
      codigo: 1018,
      precio: 10000000000,
      ubicacion: "Bogotá",
      area: "5000 m2",
      detalles: "Edificio de apartamentos de alta gama con áreas comunes, gimnasio y seguridad 24 horas.",
    },
    {
      id: 13,
      nombre: "Local en Zona Comercial",
      categoria: "Local",
      imagen: "C:\ProyectoFinal/imagenes/casa13.jpg",
      codigo: 1019,
      precio: 300000000,
      ubicacion: "Medellín",
      area: "80 m2",
      detalles: "Local en zona comercial de alto tráfico, ideal para negocios de retail o servicios.",
    },
    {
      id: 14,
      nombre: "Terreno para Desarrollo Residencial",
      categoria: "Terreno",
      imagen: "C:\ProyectoFinal/imagenes/casa14.jpg",
      codigo: 1020,
      precio: 2000000000,
      ubicacion: "Cundinamarca",
      area: "10 ha",
      detalles: "Terreno para proyecto residencial con estudio de impacto ambiental y planos aprobados.",
    },
    {
      id: 15,
      nombre: "Casa Moderna",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa15.jpg",
      codigo: 1021,
      precio: 280000000,
      ubicacion: "Antioquia",
      area: "180 m2",
      detalles: "Casa contemporánea con diseño vanguardista y áreas sociales integradas.",
    },
    {
      id: 16,
      nombre: "Apartamento en Complejo Residencial",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa16.jpg",
      codigo: 1022,
      precio: 550000000,
      ubicacion: "Bogotá",
      area: "150 m2",
      detalles: "Apartamento en complejo residencial con áreas verdes, piscina y seguridad.",
    },
    {
      id: 17,
      nombre: "Finca de Recreo",
      categoria: "Finca",
      imagen: "C:\ProyectoFinal/imagenes/casa17.jpg",
      codigo: 1023,
      precio: 700000000,
      ubicacion: "Tolima",
      area: "500 m2",
      detalles: "Finca con casa de recreo, zona BBQ, piscina y acceso a ríos y cascadas.",
    },
    {
      id: 18,
      nombre: "Edificio Comercial",
      categoria: "Edificio",
      imagen: "C:\ProyectoFinal/imagenes/casa18.jpg",
      codigo: 1024,
      precio: 15000000000,
      ubicacion: "Barranquilla",
      area: "8000 m2",
      detalles: "Edificio comercial con locales, oficinas y estacionamiento, en área de alto desarrollo empresarial.",
    },
    {
      id: 19,
      nombre: "Casa Campestre con Lago Privado",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa19.jpg",
      codigo: 1025,
      precio: 1500000000,
      ubicacion: "Caldas",
      area: "400 m2",
      detalles: "Casa campestre con amplios jardines, piscina y lago privado para actividades acuáticas.",
    },
    {
      id: 20,
      nombre: "Apartamento con Vista al Mar",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa20.jpg",
      codigo: 1026,
      precio: 900000000,
      ubicacion: "Santa Marta",
      area: "180 m2",
      detalles: "Apartamento con terraza y vista panorámica al mar, en exclusivo sector turístico.",
    },
    {
      id: 21,
      nombre: "Local en Centro Histórico",
      categoria: "Local",
      imagen: "C:\ProyectoFinal/imagenes/casa21.jpg",
      codigo: 1027,
      precio: 400000000,
      ubicacion: "Cartagena",
      area: "120 m2",
      detalles: "Local comercial en el corazón del centro histórico, ideal para negocio turístico.",
    },
    {
      id: 22,
      nombre: "Terreno Industrial en Parque Empresarial",
      categoria: "Terreno",
      imagen: "C:\ProyectoFinal/imagenes/casa22.jpg",
      codigo: 1028,
      precio: 1200000000,
      ubicacion: "Cali",
      area: "5000 m2",
      detalles: "Terreno en parque empresarial con infraestructura y servicios para industria liviana o logística.",
    },
    {
      id: 23,
      nombre: "Casa de Playa con Piscina Privada",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa23.jpg",
      codigo: 1029,
      precio: 1200000000,
      ubicacion: "Santa Marta",
      area: "300 m2",
      detalles: "Casa de playa con piscina privada, acceso directo al mar y terrazas con vista espectacular.",
    },
    {
      id: 24,
      nombre: "Apartamento en Zona Exclusiva",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa24.jpg",
      codigo: 1030,
      precio: 650000000,
      ubicacion: "Bogotá",
      area: "200 m2",
      detalles: "Apartamento en zona exclusiva, con acabados de lujo y vista a la ciudad.",
    },
    {
      id: 25,
      nombre: "Finca Productiva con Cultivos",
      categoria: "Finca",
      imagen: "C:\ProyectoFinal/imagenes/casa25.jpg",
      codigo: 1031,
      precio: 2000000000,
      ubicacion: "Antioquia",
      area: "100 ha",
      detalles: "Finca productiva con cultivos de café y plátano, y sistemas de riego instalados.",
    },
    {
      id: 26,
      nombre: "Edificio de Apartamentos",
      categoria: "Edificio",
      imagen: "C:\ProyectoFinal/imagenes/casa26.jpg",
      codigo: 1032,
      precio: 5000000000,
      ubicacion: "Cali",
      area: "3000 m2",
      detalles: "Edificio de apartamentos con parqueadero, áreas comunes y buena ubicación.",
    },
    {
      id: 27,
      nombre: "Local Comercial en Zona Turística",
      categoria: "Local",
      imagen: "C:\ProyectoFinal/imagenes/casa27.jpg",
      codigo: 1033,
      precio: 600000000,
      ubicacion: "Cartagena",
      area: "100 m2",
      detalles: "Local en zona turística de alta afluencia, perfecto para comercio o restaurante.",
    },
    {
      id: 28,
      nombre: "Terreno para Construcción",
      categoria: "Terreno",
      imagen: "C:\ProyectoFinal/imagenes/casa28.jpg",
      codigo: 1034,
      precio: 250000000,
      ubicacion: "Cundinamarca",
      area: "2000 m2",
      detalles: "Terreno listo para construcción, con servicios básicos y permisos en regla.",
    },
    {
      id: 29,
      nombre: "Casa Moderna con Jardín",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa29.jpg",
      codigo: 1035,
      precio: 400000000,
      ubicacion: "Cali",
      area: "220 m2",
      detalles: "Casa moderna con jardín, terrazas y espacios abiertos para disfrutar en familia.",
    },
    {
      id: 30,
      nombre: "Apartamento con Amenidades",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa30.jpg",
      codigo: 1036,
      precio: 500000000,
      ubicacion: "Medellín",
      area: "180 m2",
      detalles: "Apartamento en complejo con gimnasio, piscina y áreas sociales, ubicado en sector residencial.",
    },
    {
      id: 31,
      nombre: "Finca Ganadera con Instalaciones",
      categoria: "Finca",
      imagen: "C:\ProyectoFinal/imagenes/casa31.jpg",
      codigo: 1037,
      precio: 3000000000,
      ubicacion: "Valle del Cauca",
      area: "300 ha",
      detalles: "Finca ganadera con instalaciones modernas, corrales, y pastos mejorados.",
    },
    {
      id: 32,
      nombre: "Edificio Corporativo",
      categoria: "Edificio",
      imagen: "C:\ProyectoFinal/imagenes/casa32.jpg",
      codigo: 1038,
      precio: 8000000000,
      ubicacion: "Bogotá",
      area: "6000 m2",
      detalles: "Edificio corporativo de alto nivel, con tecnología de punta y ubicación estratégica.",
    },
    {
      id: 33,
      nombre: "Casa Colonial en Zona Histórica",
      categoria: "Casa",
      imagen: "C:\ProyectoFinal/imagenes/casa33.jpg",
      codigo: 1039,
      precio: 2000000000,
      ubicacion: "Cartagena",
      area: "350 m2",
      detalles: "Casa colonial restaurada en zona histórica, con patios internos y detalles arquitectónicos únicos.",
    },
    {
      id: 34,
      nombre: "Apartamento Estudio",
      categoria: "Apartamento",
      imagen: "C:\ProyectoFinal/imagenes/casa34.jpg",
      codigo: 1040,
      precio: 250000000,
      ubicacion: "Cali",
      area: "50 m2",
      detalles: "Apartamento tipo estudio, ideal para profesionales o estudiantes, en zona céntrica.",
    },
    {
      id: 35,
      nombre: "Local en Centro Empresarial",
      categoria: "Local",
      imagen: "C:\ProyectoFinal/imagenes/casa35.jpg",
      codigo: 1041,
      precio: 700000000,
      ubicacion: "Bogotá",
      area: "130 m2",
      detalles: "Local comercial en centro empresarial, ideal para oficinas o showroom.",
    },
    {
      id: 36,
      nombre: "Terreno Agrícola",
      categoria: "Terreno",
      imagen: "C:\ProyectoFinal/imagenes/casa36.jpg",
      codigo: 1042,
      precio: 500000000,
      ubicacion: "Boyacá",
      area: "50 ha",
      detalles: "Terreno agrícola con excelente tierra para cultivos, acceso a agua y caminos rurales.",
    },
    {
      id: 37,
      nombre: "Casa en Conjunto Residencial",
      categoria: "Casa",
      imagen: "https://lamansioninmobiliaria.com/wp-content/uploads/2022/06/casas-lindas-grandes-venta-alegra.jpg",
      codigo: 1043,
      precio: 350000000,
      ubicacion: "Bogotá",
      area: "180 m2",
      detalles: "Casa en conjunto residencial con vigilancia 24 horas, áreas comunes y parques infantiles.",
    },
    {
      id: 38,
      nombre: "Apartamento Amoblado",
      categoria: "Apartamento",
      imagen: "https://estaticos.elcolombiano.com/documents/10157/0/580x387/0c22/580d365/center/11101/OMFX/image_content_28780312_20170602224327.jpg",
      codigo: 1044,
      precio: 600000000,
      ubicacion: "Medellín",
      area: "160 m2",
      detalles: "Apartamento amoblado con estilo moderno, listo para habitar en zona residencial.",
    },
    {
      id: 39,
      nombre: "Finca de Café",
      categoria: "Finca",
      imagen: "https://perfectdailygrind.com/es/wp-content/uploads/sites/2/2021/02/finca-de-cafe%CC%81-grande-1.jpg",
      codigo: 1045,
      precio: 1000000000,
      ubicacion: "Quindío",
      area: "200 ha",
      detalles: "Finca de café en plena producción, con beneficios y almacenes, ideal para inversión agrícola.",
    },
    {
      id: 40,
      nombre: "Edificio de Oficinas Inteligente",
      categoria: "Edificio",
      imagen: "https://img.pagecloud.com/tWFxVn3lFI4lfAvxD1J_kzPjoIA=/1000x0/filters:no_upscale()/zegens/8cf8b3ad-61cb-4908-df02-47ae838a9198.jpeg",
      codigo: 1046,
      precio: 12000000000,
      ubicacion: "Cali",
      area: "7000 m2",
      detalles: "Edificio de oficinas inteligente con sistemas automatizados, salas de reuniones y auditorios.",
    },
    {
      id: 41,
      nombre: "Casa de Montaña",
      categoria: "Casa",
      imagen: "https://revistaaxxis.com.co/wp-content/uploads/2021/07/Captura-de-pantalla-2021-07-07-a-las-16.53.28.png",
      codigo: 1047,
      precio: 900000000,
      ubicacion: "Boyacá",
      area: "250 m2",
      detalles: "Casa de montaña con vista a paisajes naturales, chimenea y áreas verdes.",
    },
    {
      id: 42,
      nombre: "Apartamento en Torre de Lujo",
      categoria: "Apartamento",
      imagen: "https://www.curridabatproperties.com/wp-content/uploads/2021/04/PHOTO-2021-04-13-10-38-38-4.jpg",
      codigo: 1048,
      precio: 800000000,
      ubicacion: "Bogotá",
      area: "220 m2",
      detalles: "Apartamento en torre de lujo con amenities exclusivas, seguridad y vistas impresionantes.",
    },
    {
      id: 43,
      nombre: "Local Comercial en Avenida Principal",
      categoria: "Local",
      imagen: "https://http2.mlstatic.com/D_NQ_NP_788075-MCO72938506627_112023-O.webp",
      codigo: 1049,
      precio: 900000000,
      ubicacion: "Medellín",
      area: "170 m2",
      detalles: "Local en avenida principal de alto tráfico, ideal para negocios que buscan visibilidad.",
    },
    {
      id: 44,
      nombre: "Terreno para Proyecto Eco-turístico",
      categoria: "Terreno",
      imagen: "https://www.inversioneshc.com/uploads/LO-PE-013-lote-en-venta-condominio-penol-antioquia-colombia-3f9f74.jpg",
      codigo: 1050,
      precio: 1500000000,
      ubicacion: "Cundinamarca",
      area: "50 ha",
      detalles: "Terreno para desarrollo eco-turístico, con acceso a reservas naturales y paisajes exóticos.",
    },
    {
      id: 45,
      nombre: "Casa Inteligente",
      categoria: "Casa",
      imagen: "https://realestatemarket.com.mx/images/2024/01-enero/10/Renueva-tu-hogar-con-estos-5-dispositivos-inteligentes.jpg",
      codigo: 1051,
      precio: 2500000000,
      ubicacion: "Bogotá",
      area: "300 m2",
      detalles: "Casa inteligente con domótica, seguridad avanzada y eficiencia energética.",
    },
    {
      id: 46,
      nombre: "Apartamento en Complejo Residencial de Lujo",
      categoria: "Apartamento",
      imagen: "https://static.vecteezy.com/system/resources/previews/031/401/874/non_2x/luxury-modern-residential-apartment-building-complex-photo.JPG",
      codigo: 1052,
      precio: 1000000000,
      ubicacion: "Medellín",
      area: "240 m2",
      detalles: "Apartamento en complejo residencial de lujo, con amenities premium y excelente ubicación.",
    },
    {
      id: 47,
      nombre: "Finca Agroecológica",
      categoria: "Finca",
      imagen: "https://www.researchgate.net/profile/Salvador-Partida/publication/352572478/figure/fig2/AS:1037196429651969@1624298307802/Figura-2-Vista-aerea-de-Finca-Agroecologica-Don-Gervasio.png",
      codigo: 1053,
      precio: 1500000000,
      ubicacion: "Tolima",
      area: "80 ha",
      detalles: "Finca agroecológica con cultivos orgánicos, certificaciones y prácticas sostenibles.",
    },
    {
      id: 48,
      nombre: "Edificio de Consultorios Médicos",
      categoria: "Edificio",
      imagen: "edificio_consultorios_medicos.jpg",
      codigo: 1054,
      precio: 5000000000,
      ubicacion: "Bogotá",
      area: "4000 m2",
      detalles: "Edificio de consultorios médicos con áreas de espera, ascensores y equipamiento especializado.",
    },
    {
      id: 49,
      nombre: "Local Comercial con Bodega",
      categoria: "Local",
      imagen: "https://www.bienesonline.com/chile/photos/local-comercial-con-bodega-14249858983.jpg",
      codigo: 1055,
      precio: 1200000000,
      ubicacion: "Cali",
      area: "300 m2",
      detalles: "Local comercial con bodega incluida, ideal para almacenamiento y venta al por mayor.",
    },
    {
      id: 50,
      nombre: "Terreno con Viñedos",
      categoria: "Terreno",
      imagen: "https://img.freepik.com/fotos-premium/terreno-vinedos-concepto-vinedo-vino-enologia-plantas-alcohol-tierra-rural-negocios_325364-2394.jpg",
      codigo: 1056,
      precio: 2000000000,
      ubicacion: "Boyacá",
      area: "70 ha",
      detalles: "Terreno con viñedos en producción, bodegas y facilidades para la elaboración de vino.",
    }
  ]
}
